# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Spot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spot
  pod 'Alamofire', '~> 4.0'
  pod 'ObjectMapper', '~> 2.2'
  pod 'AlamofireObjectMapper', '~> 4.0'

  target 'SpotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpotUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
